baseURL = 'http://localhost:1313/'
enableRobotsTXT = true
languageCode = 'en-us'
defaultContentLanguage = "en"
pygmentsStyle = 'monokai'
theme = 'gokarna'
title = 'eiakoji.me'
ShowBackToTopButton = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/me.jpeg"
  image = "/images/posts/eiakoji_screenshot.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Software Architect | Tech Enthusiast"
  subDescription = "For my unconquerable soul, I thank whatever gods may be. Of my fate, I am master."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["eiakojime"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  # showPostsOnHomePage = ""

  # Footer text
  footer = "eiakoji.me | Powered by Hugo on Netlify"

  togglePreviousAndNextButtons = "false"

  # https://www.iconfinder.com/icons/
  socialIcons = [
    {name = "github", url = "https://github.com/eiakoji-me"},
    {name = "linkedin", url = "https://www.linkedin.com/in/ezekiel-inalegwu-akoji/"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/7411342/koji-dinfinte"},
    {name = "email", url = "akojimsg@gmail.com"},
    {name = "medium", url = "https://medium.com/@akojimsg"},
    {name = "devto", url = "https://dev.to/akojimsg"},
  ]

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "Home"
    url = "/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='home'></span>"
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Display name
    name = "Home"
    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/eiakoji-me"
    weight = 6
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
